### ISSUE TITLE
Forgot to deploy new version to Pub ;)

### ISSUE THREAD

**Issue by bounty1342** [LunaGao/flag_flutter#63]

**Comment by bounty1342** [comment]
@LunaGao Could you please upload the version to Pubspec ?

Thx and happy new year.

**Comment by ghost** [comment]
Can you guys update to flutter_svg: ^1.0.0 it causes build errors

**Comment by bounty1342** [comment]
@lucmichalski, if in a rush, you can still do.

```
dependency_overrides:
  flag:
    git: 
      url: https://github.com/LunaGao/flag_flutter.git
      ref: stable
```
